// @ts-nocheck
import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{CognitoIdentityClient}from"@aws-sdk/client-cognito-identity";
import{CognitoIdentityProviderClient,InitiateAuthCommand,RespondToAuthChallengeCommand}from"@aws-sdk/client-cognito-identity-provider";
import{fromCognitoIdentityPool}from"@aws-sdk/credential-provider-cognito-identity";
import{SignatureV4}from"@aws-sdk/signature-v4";import{HttpRequest}from"@aws-sdk/protocol-http";import{Sha256}from"@aws-crypto/sha256-js";import"./style.css";
const api=import.meta.env.VITE_API_URL,region=import.meta.env.VITE_AWS_REGION||"us-east-1",pool=import.meta.env.VITE_COGNITO_USER_POOL_ID,clientId=import.meta.env.VITE_COGNITO_CLIENT_ID,identityPool=import.meta.env.VITE_COGNITO_IDENTITY_POOL_ID;
const state=(q:any)=>q.status==="ERROR"||q.utilizationPercent>=95?"critical":q.status==="WARN"||q.utilizationPercent>=80?"warning":"healthy";
function App(){const[items,setItems]=useState<any[]>([]),[summary,setSummary]=useState<any>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[nextPassword,setNextPassword]=useState(""),[challenge,setChallenge]=useState<any>(),[token,setToken]=useState(sessionStorage.getItem("qm-id-token"));
const complete=(t:string)=>{credentialsProvider=undefined;sessionStorage.setItem("qm-id-token",t);setToken(t);setChallenge(undefined);setPassword("");setNextPassword("")};
const login=async(e:any)=>{e.preventDefault();setError("");try{const c=new CognitoIdentityProviderClient({region});let r;if(challenge)r=await c.send(new RespondToAuthChallengeCommand({ClientId:clientId,ChallengeName:challenge.name,Session:challenge.session,ChallengeResponses:{USERNAME:email,NEW_PASSWORD:nextPassword}}));else r=await c.send(new InitiateAuthCommand({AuthFlow:"USER_PASSWORD_AUTH",ClientId:clientId,AuthParameters:{USERNAME:email,PASSWORD:password}}));if(r.AuthenticationResult?.IdToken)complete(r.AuthenticationResult.IdToken);else if(r.ChallengeName&&r.Session){setChallenge({name:r.ChallengeName,session:r.Session});setError("Your temporary password must be changed.")}else throw Error("Sign-in did not return an ID token")}catch(x){setError(x instanceof Error?x.message:"Sign-in failed")}};
let credentialsProvider:any;
const signed=async(path:string)=>{credentialsProvider??=fromCognitoIdentityPool({client:new CognitoIdentityClient({region})as any,identityPoolId:identityPool,logins:{[`cognito-idp.${region}.amazonaws.com/${pool}`]:token}});const u=new URL(`${api}${path}`),req=new HttpRequest({method:"GET",protocol:u.protocol,hostname:u.hostname,path:u.pathname+u.search,headers:{host:u.hostname}}),s=await new SignatureV4({credentials:credentialsProvider,region,service:"lambda",sha256:Sha256}).sign(req),headers={...s.headers};delete headers.host;return fetch(u,{headers})};
const refresh=async()=>{setBusy(true);setError("");try{const[a,b]=await Promise.all([signed("/summary"),signed("/quotas?limit=500")]);if(!a.ok||!b.ok)throw Error(a.status===403?"You are not authorized to view quota data":"Dashboard data unavailable");setSummary((await a.json()).items?.[0]||{});setItems((await b.json()).items||[])}catch(x){credentialsProvider=undefined;sessionStorage.removeItem("qm-id-token");setToken(null);setError("Your sign-in session expired or could not reach the API. Please sign in again.")}finally{setBusy(false)}};useEffect(()=>{if(token)refresh()},[token]);
if(!token)return <main className="login"><form onSubmit={login} className="panel"><p className="eyebrow">QUOTA MONITOR</p><h1>{challenge?"Set a new password":"Sign in"}</h1>{error&&<div className="alert" role="alert">{error}</div>}{!challenge&&<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{challenge?<label>New password<input required minLength={14} type="password" value={nextPassword} onChange={e=>setNextPassword(e.target.value)}/></label>:<label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button> {challenge?"Set password":"Sign in"}</button></form></main>;
const visible=items.filter(q=>`${q.serviceCode} ${q.quotaName} ${q.accountId} ${q.region}`.toLowerCase().includes(filter.toLowerCase()));return <main><header><div><p className="eyebrow">QUOTA MONITOR</p><h1>Organization quota health</h1></div><button onClick={refresh} disabled={busy}>{busy?"Refreshing…":"Refresh data"}</button></header>{error&&<div className="alert" role="alert">{error}</div>}<section className="cards">{[["Total quotas",summary.totalQuotas||0,""],["Healthy",summary.healthy||0,"healthy"],["Warning",summary.warning||0,"warning"],["Critical",summary.critical||0,"critical"],["Accounts",summary.accounts||0,""],["Regions",summary.regions||0,""]].map(x=><article className="card" key={String(x[0])}><span>{x[0]}</span><strong className={String(x[2])}>{x[1]}</strong></article>)}</section><section className="panel"><div className="panelHead"><h2>Quota details</h2><input aria-label="Filter quotas" placeholder="Filter quotas…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="tableWrap"><table><thead><tr><th>Service / quota</th><th>Account</th><th>Region</th><th>Usage</th><th>Status</th><th>Observed</th></tr></thead><tbody>{visible.map(q=><tr key={q.quotaId}><td><strong>{q.serviceCode}</strong><br/><span className="muted">{q.quotaName||q.quotaId}</span></td><td>{q.accountId}</td><td>{q.region}</td><td>{q.currentUtilization} / {q.quotaValue}</td><td><span className={`badge ${state(q)}`}>{state(q)}</span></td><td>{q.timestamp}</td></tr>)}</tbody></table></div></section></main>};createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
