// @ts-nocheck
import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";
import { CognitoIdentityProviderClient, InitiateAuthCommand, RespondToAuthChallengeCommand } from "@aws-sdk/client-cognito-identity-provider";
import { fromCognitoIdentityPool } from "@aws-sdk/credential-provider-cognito-identity";
import { SignatureV4 } from "@aws-sdk/signature-v4";
import { HttpRequest } from "@aws-sdk/protocol-http";
import { Sha256 } from "@aws-crypto/sha256-js";
import { clearSession, readSession, SessionExpiredError, tokenExpiresSoon, writeSession } from "./auth";
import "./style.css";

const quotaApi = import.meta.env.VITE_API_URL, billingApi = import.meta.env.VITE_BILLING_API_URL, region = import.meta.env.VITE_AWS_REGION || "us-east-1", pool = import.meta.env.VITE_COGNITO_USER_POOL_ID, clientId = import.meta.env.VITE_COGNITO_CLIENT_ID, identityPool = import.meta.env.VITE_COGNITO_IDENTITY_POOL_ID;
const provider = `cognito-idp.${region}.amazonaws.com/${pool}`, cognito = new CognitoIdentityProviderClient({ region }); let credentialsProvider: any;
const quotaState = (q: any) => q.status === "ERROR" || q.utilizationPercent >= 95 ? "critical" : q.status === "WARN" || q.utilizationPercent >= 80 ? "warning" : "healthy";
const freeState = (q: any) => q.ActualUsage >= q.Limit ? "critical" : q.ForecastUsage / Math.max(q.Limit, 1) >= .8 ? "warning" : "healthy";
const money = (n: number, c = "USD") => new Intl.NumberFormat(undefined, { style: "currency", currency: c, maximumFractionDigits: 2 }).format(n || 0);
const isAdmin = (token?: string) => { try { return (JSON.parse(atob((token ?? "").split(".")[1].replace(/-/g, "+").replace(/_/g, "/")))["cognito:groups"] ?? []).includes("BillingAdmins"); } catch { return false; } };
async function session() { const s = readSession(); if (!s) throw new SessionExpiredError(); if (!tokenExpiresSoon(s.idToken)) return s; try { const r = await cognito.send(new InitiateAuthCommand({ AuthFlow: "REFRESH_TOKEN_AUTH", ClientId: clientId, AuthParameters: { REFRESH_TOKEN: s.refreshToken } })); if (!r.AuthenticationResult?.IdToken) throw new Error(); const n = { idToken: r.AuthenticationResult.IdToken, refreshToken: r.AuthenticationResult.RefreshToken || s.refreshToken }; writeSession(n); credentialsProvider = undefined; return n; } catch { clearSession(); credentialsProvider = undefined; throw new SessionExpiredError(); } }
async function signed(base: string, path: string) { if (!base) throw Error("Billing dashboard configuration is unavailable."); const s = await session(); credentialsProvider ??= fromCognitoIdentityPool({ client: new CognitoIdentityClient({ region }) as any, identityPoolId: identityPool, logins: { [provider]: s.idToken } }); const url = new URL(`${base.replace(/\/+$/, "")}${path}`), request = new HttpRequest({ method: "GET", protocol: url.protocol, hostname: url.hostname, path: url.pathname, query: Object.fromEntries(url.searchParams.entries()), headers: { host: url.hostname } }), sig = await new SignatureV4({ credentials: credentialsProvider, region, service: "lambda", sha256: Sha256 }).sign(request), headers = { ...sig.headers }; delete headers.host; return fetch(url, { headers }); }
const Card = ({ label, value }: any) => <article className="card"><span>{label}</span><strong>{value}</strong></article>;
function App() {
  const [current, setCurrent] = useState(readSession()), [view, setView] = useState("quotas"), [items, setItems] = useState<any[]>([]), [summary, setSummary] = useState<any>({}), [bill, setBill] = useState<any>({}), [costs, setCosts] = useState<any[]>([]), [free, setFree] = useState<any[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(""), [filter, setFilter] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [nextPassword, setNextPassword] = useState(""), [challenge, setChallenge] = useState<any>();
  const admin = isAdmin(current?.idToken), signOut = () => { clearSession(); credentialsProvider = undefined; setCurrent(null); setView("quotas"); };
  const complete = (r: any) => { if (!r.IdToken || !r.RefreshToken) throw new SessionExpiredError("Sign-in did not return a complete session."); const n = { idToken: r.IdToken, refreshToken: r.RefreshToken }; writeSession(n); credentialsProvider = undefined; setCurrent(n); setChallenge(undefined); setPassword(""); setNextPassword(""); };
  const login = async (e: any) => { e.preventDefault(); setError(""); try { const r = challenge ? await cognito.send(new RespondToAuthChallengeCommand({ ClientId: clientId, ChallengeName: challenge.name, Session: challenge.session, ChallengeResponses: { USERNAME: email, NEW_PASSWORD: nextPassword } })) : await cognito.send(new InitiateAuthCommand({ AuthFlow: "USER_PASSWORD_AUTH", ClientId: clientId, AuthParameters: { USERNAME: email, PASSWORD: password } })); if (r.AuthenticationResult?.IdToken) complete(r.AuthenticationResult); else if (r.ChallengeName && r.Session) { setChallenge({ name: r.ChallengeName, session: r.Session }); setError("Your temporary password must be changed."); } else throw Error("Sign-in did not return an ID token"); } catch (x) { setError(x instanceof Error ? x.message : "Sign-in failed"); } };
  const refresh = async () => { setBusy(true); setError(""); try { if (view === "quotas") { const [a, b] = await Promise.all([signed(quotaApi, "/summary"), signed(quotaApi, "/quotas?limit=500")]); if (!a.ok || !b.ok) throw Object.assign(Error("Quota data request failed."), { status: !a.ok ? a.status : b.status }); setSummary((await a.json()).items?.[0] || {}); setItems((await b.json()).items || []); } else { const [a, b] = await Promise.all([signed(billingApi, "/summary"), signed(billingApi, view === "billing" ? "/costs?limit=500" : "/free-tier?limit=500")]); if (!a.ok || !b.ok) throw Object.assign(Error("Billing data request failed."), { status: !a.ok ? a.status : b.status }); setBill((await a.json()).items?.[0] || {}); if (view === "billing") setCosts((await b.json()).items || []); else setFree((await b.json()).items || []); } } catch (x) { credentialsProvider = undefined; const status = Number((x as any)?.status || 0); if (x instanceof SessionExpiredError || status === 401 || status === 403) { signOut(); setError("Your sign-in session expired or you are not authorized to view this data. Please sign in again."); } else setError(`${x instanceof Error ? x.message : "Could not refresh dashboard data."} Use Refresh data to retry.`); } finally { setBusy(false); } };
  useEffect(() => { if (current) refresh(); }, [current, view]);
  const quotas = useMemo(() => items.filter(q => `${q.serviceCode} ${q.quotaName} ${q.accountId} ${q.region}`.toLowerCase().includes(filter.toLowerCase())), [items, filter]), serviceCosts = useMemo(() => costs.filter(q => String(q.service).toLowerCase().includes(filter.toLowerCase())), [costs, filter]), freeTier = useMemo(() => free.filter(q => `${q.Service} ${q.UsageType} ${q.Region}`.toLowerCase().includes(filter.toLowerCase())), [free, filter]);
  if (!current) return <main className="login"><form onSubmit={login} className="panel"><p className="eyebrow">QUOTA MONITOR</p><h1>{challenge ? "Set a new password" : "Sign in"}</h1>{error && <div className="alert" role="alert">{error}</div>}{!challenge && <label>Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label>}{challenge ? <label>New password<input required minLength={14} type="password" value={nextPassword} onChange={e => setNextPassword(e.target.value)} /></label> : <label>Password<input required type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>}<button>{challenge ? "Set password" : "Sign in"}</button></form></main>;
  return <main><header><div><p className="eyebrow">QUOTA MONITOR</p><h1>Organization operations</h1><nav aria-label="Dashboard sections"><button className={view === "quotas" ? "active" : "secondary"} onClick={() => setView("quotas")}>Quotas</button>{admin && <><button className={view === "billing" ? "active" : "secondary"} onClick={() => setView("billing")}>Billing</button><button className={view === "free-tier" ? "active" : "secondary"} onClick={() => setView("free-tier")}>Free Tier</button></>}</nav></div><div className="actions"><button className="secondary" onClick={signOut}>Sign out</button><button onClick={refresh} disabled={busy}>{busy ? "Refreshing…" : "Refresh data"}</button></div></header>{error && <div className="alert" role="alert">{error}</div>}
  {view === "quotas" && <><section className="cards">{[["Total quotas", summary.totalQuotas || 0, ""], ["Healthy", summary.healthy || 0, "healthy"], ["Warning", summary.warning || 0, "warning"], ["Critical", summary.critical || 0, "critical"], ["Accounts", summary.accounts || 0, ""], ["Regions", summary.regions || 0, ""]].map(x => <article className="card" key={x[0]}><span>{x[0]}</span><strong className={x[2]}>{x[1]}</strong></article>)}</section><section className="panel"><div className="panelHead"><h2>Quota details</h2><input aria-label="Filter quotas" placeholder="Filter quotas…" value={filter} onChange={e => setFilter(e.target.value)} /></div><div className="tableWrap"><table><thead><tr><th>Service / quota</th><th>Account</th><th>Region</th><th>Usage</th><th>Status</th><th>Observed</th></tr></thead><tbody>{quotas.map(q => <tr key={q.quotaId}><td><strong>{q.serviceCode}</strong><br /><span className="muted">{q.quotaName || q.quotaId}</span></td><td>{q.accountId}</td><td>{q.region}</td><td>{q.currentUtilization} / {q.quotaValue}</td><td><span className={`badge ${quotaState(q)}`}>{quotaState(q)}</span></td><td>{q.timestamp}</td></tr>)}</tbody></table>{!quotas.length && <p className="empty">No quota records are available yet.</p>}</div></section></>}
  {view === "billing" && <><section className="cards"><Card label="Month to date" value={money(bill.currentTotal, bill.currency)} /><Card label="Month-end forecast" value={money(bill.forecastTotal, bill.currency)} /><Card label="Cost services" value={bill.costServiceCount || 0} /><Card label="Collected" value={bill.collectedAt ? new Date(bill.collectedAt).toLocaleDateString() : "No data"} /></section><section className="panel"><div className="panelHead"><h2>Costs by service</h2><input aria-label="Filter costs" placeholder="Filter services…" value={filter} onChange={e => setFilter(e.target.value)} /></div><table><thead><tr><th>Service</th><th>Month to date</th><th>Month-end forecast</th></tr></thead><tbody>{serviceCosts.map(q => <tr key={q.RecordKey}><td>{q.service}</td><td>{money(q.currentCost, q.currency)}</td><td>{money(q.forecastCost, q.currency)}</td></tr>)}</tbody></table>{!serviceCosts.length && <p className="empty">No cost snapshot is available yet.</p>}</section></>}
  {view === "free-tier" && <><section className="cards"><Card label="Tracked offers" value={bill.freeTierCount || 0} /><Card label="Snapshot" value={bill.collectedAt ? new Date(bill.collectedAt).toLocaleDateString() : "No data"} /><Card label="Data source" value="Management account" /></section><section className="panel"><div className="panelHead"><h2>Free Tier usage</h2><input aria-label="Filter Free Tier usage" placeholder="Filter Free Tier…" value={filter} onChange={e => setFilter(e.target.value)} /></div><div className="tableWrap"><table><thead><tr><th>Service / usage</th><th>Region</th><th>Current</th><th>Forecast</th><th>Allowance</th><th>Status</th></tr></thead><tbody>{freeTier.map(q => <tr key={q.RecordKey}><td><strong>{q.Service}</strong><br /><span className="muted">{q.UsageType}</span></td><td>{q.Region}</td><td>{q.ActualUsage} {q.Unit}</td><td>{q.ForecastUsage} {q.Unit}</td><td>{q.Limit} {q.Unit}</td><td><span className={`badge ${freeState(q)}`}>{freeState(q) === "critical" ? "Exceeded" : freeState(q) === "warning" ? "Forecast warning" : "Healthy"}</span></td></tr>)}</tbody></table></div>{!freeTier.length && <p className="empty">No Free Tier usage is available yet.</p>}</section></>}
  </main>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
